version: '3.4'

services:
  bookify.api:
    image: ${DOCKER_REGISTRY-}bookifyapi
    container_name: Bookify.Api
    build:
      context: .
      dockerfile: src/Bookify.Api/Dockerfile
    depends_on:
      - bookify-db

  bookify-db:
    image: postgres:latest
    container_name: Bookify.Db
    environment:
      - POSTGRES_DB=bookify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql
    ports:
      - 5432:5432

  bookify-idp-db:
    image: postgres:latest
    container_name: Bookify.Identity.Db
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/identity-database:/var/lib/postgresql
    ports:
      - 5434:5432

  bookify-idp:
    image: quay.io/keycloak/keycloak:latest
    container_name: Bookify.Identity
    command: start-dev --import-realm
    depends_on:
      - bookify-idp-db
    restart: always
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
      - KC_DB=postgres
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      - KC_DB_SCHEMA=keycloak
      - KC_DB_URL_HOST=bookify-idp-db
      - KC_DB_PORT=5432
      - KC_DB_URL_DATABASE=keycloak
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files/bookify-realm-export.json:/opt/keycloak/data/import/realm.json
    ports:
      - 18080:8080

  bookify-seq:
    image: datalust/seq:latest
    container_name: Bookify.Seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=SuperSecurePassword123!
    ports:
      - 5341:5341
      - 8081:80

  bookify-redis:
    image: redis:latest
    container_name: Bookify.Redis
    restart: always
    ports:
      - '6379:6379'
